version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: 'mysql:latest'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: main
    ports:
      - '3306'

  mailcatcher:
    image: dockage/mailcatcher:0.7.1
    ports:
    - "1080:1080"
    - "1025:1025"

  phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin_portfolio
        restart: always
        depends_on:
            - database
        ports:
            - 8085:80
        environment:
            PMA_HOST: database
            

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
